In [1]:
import cv2
from mmpose.apis import MMPoseInferencer
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go

In [2]:
# build the inferencer with 3d model alias
inferencer = MMPoseInferencer(pose3d="human3d")

img_path = "steve.jpg"

result_generator = inferencer(img_path, out_dir="predictions")
result = next(result_generator)



Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/body_3d_keypoint/pose_lift/h36m/motionbert_ft_h36m-d80af323_20230531.pth
01/09 18:03:24 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-body7_pt-body7_420e-256x192-e48f03d0_20230504.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth
01/09 18:03:25 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "function" registry tree. As a workaround, the current "functio

/home/shaunthesheep/anaconda3/envs/mmpose/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1702400200538/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


01/09 18:03:25 - mmengine - INFO - the output image has been saved at predictions/visualizations/steve.jpg


In [3]:
points = np.array(result['predictions'][0][0]['keypoints'])

In [42]:
for ix, point in result['predictions'][0][0]['keypoints']:
    

[[-0.0, 0.0, 0.5945200324058533],
 [-0.09653881937265396, -0.10489518940448761, 0.6183314323425293],
 [-0.28601977229118347, 0.2887641489505768, 0.34015199542045593],
 [0.012841308489441872, -0.018466230481863022, 0.0],
 [0.09614648669958115, 0.10300170630216599, 0.5683420300483704],
 [-0.010804443620145321, 0.48717013001441956, 0.398555189371109],
 [0.06678662449121475, 0.4773820638656616, 0.0431172251701355],
 [0.17250806093215942, -0.060421861708164215, 0.8122292757034302],
 [0.347349613904953, -0.1685224324464798, 1.0317211151123047],
 [0.2839680314064026, -0.10248693823814392, 1.2149009704589844],
 [0.30861353874206543, -0.22477194666862488, 1.2453720569610596],
 [0.4995904564857483, -0.041900575160980225, 1.0127899646759033],
 [0.3580944836139679, 0.18112318217754364, 1.174966812133789],
 [0.24327197670936584, 0.04366384819149971, 1.3300856351852417],
 [0.1752617210149765, -0.21062736213207245, 1.0487459897994995],
 [-0.0390009768307209, 0.010913022793829441, 1.0431119203567505],

In [4]:
points.shape

(17, 3)

In [44]:
#make a 3d point plot from given x,y,z coordinates


# Define the coordinates
x = points[:,0]
y = points[:,1]
z = points[:,2]

# Create a 3D scatter plot
fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z, mode='markers')])

# Display the plot
fig.show()


In [7]:
from mmpose.datasets import wholebody3d

In [13]:
from configs._base_.datasets.h36m import dataset_info

In [45]:
dataset_info['skeleton_info']

{0: {'link': ('root', 'left_hip'), 'id': 0, 'color': [0, 255, 0]},
 1: {'link': ('left_hip', 'left_knee'), 'id': 1, 'color': [0, 255, 0]},
 2: {'link': ('left_knee', 'left_foot'), 'id': 2, 'color': [0, 255, 0]},
 3: {'link': ('root', 'right_hip'), 'id': 3, 'color': [255, 128, 0]},
 4: {'link': ('right_hip', 'right_knee'), 'id': 4, 'color': [255, 128, 0]},
 5: {'link': ('right_knee', 'right_foot'), 'id': 5, 'color': [255, 128, 0]},
 6: {'link': ('root', 'spine'), 'id': 6, 'color': [51, 153, 255]},
 7: {'link': ('spine', 'thorax'), 'id': 7, 'color': [51, 153, 255]},
 8: {'link': ('thorax', 'neck_base'), 'id': 8, 'color': [51, 153, 255]},
 9: {'link': ('neck_base', 'head'), 'id': 9, 'color': [51, 153, 255]},
 10: {'link': ('thorax', 'left_shoulder'), 'id': 10, 'color': [0, 255, 0]},
 11: {'link': ('left_shoulder', 'left_elbow'), 'id': 11, 'color': [0, 255, 0]},
 12: {'link': ('left_elbow', 'left_wrist'), 'id': 12, 'color': [0, 255, 0]},
 13: {'link': ('thorax', 'right_shoulder'), 'id': 13

In [19]:
keypoint_info = dataset_info['keypoint_info']

skeleton_info = dataset_info['skeleton_info']



In [20]:
from pydantic import BaseModel
from typing import List, Tuple

class Keypoint(BaseModel):
    name: str
    id: int
    color: List[int]
    type: str
    swap: str

class Skeleton(BaseModel):
    link: Tuple[str, str]
    id: int
    color: List[int]

# Convert the dictionaries to Pydantic models
keypoint_models = {k: Keypoint(**v) for k, v in keypoint_info.items()}
skeleton_models = {k: Skeleton(**v) for k, v in skeleton_info.items()}

In [26]:
skeleton_models

{0: Skeleton(link=('root', 'left_hip'), id=0, color=[0, 255, 0]),
 1: Skeleton(link=('left_hip', 'left_knee'), id=1, color=[0, 255, 0]),
 2: Skeleton(link=('left_knee', 'left_foot'), id=2, color=[0, 255, 0]),
 3: Skeleton(link=('root', 'right_hip'), id=3, color=[255, 128, 0]),
 4: Skeleton(link=('right_hip', 'right_knee'), id=4, color=[255, 128, 0]),
 5: Skeleton(link=('right_knee', 'right_foot'), id=5, color=[255, 128, 0]),
 6: Skeleton(link=('root', 'spine'), id=6, color=[51, 153, 255]),
 7: Skeleton(link=('spine', 'thorax'), id=7, color=[51, 153, 255]),
 8: Skeleton(link=('thorax', 'neck_base'), id=8, color=[51, 153, 255]),
 9: Skeleton(link=('neck_base', 'head'), id=9, color=[51, 153, 255]),
 10: Skeleton(link=('thorax', 'left_shoulder'), id=10, color=[0, 255, 0]),
 11: Skeleton(link=('left_shoulder', 'left_elbow'), id=11, color=[0, 255, 0]),
 12: Skeleton(link=('left_elbow', 'left_wrist'), id=12, color=[0, 255, 0]),
 13: Skeleton(link=('thorax', 'right_shoulder'), id=13, color=[25

In [52]:
keypoint_models[0].name

'root'

In [53]:
name2id = {}

for kpt in keypoint_models:
    kpt = keypoint_models[kpt]
    name2id[kpt.name] = kpt.id
    
name2id

{'root': 0,
 'right_hip': 1,
 'right_knee': 2,
 'right_foot': 3,
 'left_hip': 4,
 'left_knee': 5,
 'left_foot': 6,
 'spine': 7,
 'thorax': 8,
 'neck_base': 9,
 'head': 10,
 'left_shoulder': 11,
 'left_elbow': 12,
 'left_wrist': 13,
 'right_shoulder': 14,
 'right_elbow': 15,
 'right_wrist': 16}

In [48]:
skeleton_models[0].link[0]

'root'

In [46]:
connections = []

In [57]:
for link in skeleton_models:
    link = skeleton_models[link]
    connection = [name2id[link.link[0]], name2id[link.link[1]]]
    connections.append(connection)

In [58]:
connections

[[0, 4],
 [4, 5],
 [5, 6],
 [0, 1],
 [1, 2],
 [2, 3],
 [0, 7],
 [7, 8],
 [8, 9],
 [9, 10],
 [8, 11],
 [11, 12],
 [12, 13],
 [8, 14],
 [14, 15],
 [15, 16]]

In [60]:
#make a 3d point plot from given x,y,z coordinates


# Define the coordinates
x = points[:,0]
y = points[:,1]
z = points[:,2]

# Create a 3D scatter plot
fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z, mode='markers')])

# Add lines for each connection
for connection in connections:
    fig.add_trace(
        go.Scatter3d(
            x=[x[connection[0]], x[connection[1]]],
            y=[y[connection[0]], y[connection[1]]],
            z=[z[connection[0]], z[connection[1]]],
            mode='lines',
        )
    )


# Display the plot
fig.show()


In [78]:
frames = []
df_rows = []

In [84]:
#read video using cv2
cap = cv2.VideoCapture('coach480.mp4')


while (cap.isOpened()):
    _, frame = cap.read()
    
    if not _:
        break
    
    frames
    
    
    
    

In [95]:
result_generator = inferencer(frames, out_dir="predictions")

In [96]:
rows = []

In [97]:
next(result_generator)

01/09 20:15:02 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg


defaultdict(list,
            {'visualization': [],
             'predictions': [[{'keypoints': [[-0.0, 0.0, 0.6717525720596313],
                 [0.07467737048864365,
                  -0.028070135042071342,
                  0.6715697646141052],
                 [0.11087720096111298,
                  0.02510574646294117,
                  0.3233090937137604],
                 [0.1637280285358429, 0.062361907213926315, 0.0],
                 [-0.08033276349306107,
                  0.02711647003889084,
                  0.6805493831634521],
                 [-0.07199389487504959,
                  0.062087178230285645,
                  0.35492372512817383],
                 [-0.05779785290360451,
                  0.10631536692380905,
                  0.04812270402908325],
                 [-0.013464965857565403,
                  0.0024648832622915506,
                  0.8729780316352844],
                 [-0.019340576604008675,
                  -0.07203830033540726,
         

In [98]:
rows = []

In [99]:
ix = 0
for result in result_generator:
    points = np.array(result['predictions'][0][0]['keypoints'])
    rows.append([ix, points[:,0], points[:,1], points[:,2]])
    ix+=1
    
    
    

01/09 20:15:04 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:04 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:05 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:05 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:05 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:06 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:06 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:06 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:07 - mmengine - INFO - the output image has been saved at predictions/visualizations/000000.jpg
01/09 20:15:07 - mmengine - 

In [100]:
rows

[[0,
  array([-0.        ,  0.07467737,  0.11087707,  0.16372803, -0.08033288,
         -0.07199389, -0.05779785, -0.01346509, -0.01934058, -0.11573303,
         -0.10925207, -0.14579529, -0.18710499, -0.08400439,  0.11437292,
          0.17950268,  0.07061987]),
  array([ 0.        , -0.02807014,  0.02510567,  0.06236178,  0.02711649,
          0.06208707,  0.10631525,  0.00246486, -0.07203839, -0.10775881,
         -0.09820108, -0.03859142,  0.00587283,  0.06856572, -0.03285078,
          0.00865254, -0.03464519]),
  array([0.67175269, 0.67156988, 0.32330909, 0.        , 0.6805495 ,
         0.35492373, 0.04812282, 0.87297815, 1.08201504, 1.2257309 ,
         1.26569843, 1.09897614, 0.85642481, 0.71426827, 1.07843256,
         0.84877431, 0.71225768])],
 [1,
  array([-0.        ,  0.07479309,  0.1111875 ,  0.16410913, -0.08026758,
         -0.07171887, -0.05757092, -0.01473218, -0.02294922, -0.11568274,
         -0.10910095, -0.14541492, -0.18698536, -0.08378601,  0.10690796,
       

In [105]:
df = pd.DataFrame(rows, columns=['frame','x','y','z'])

In [104]:
import plotly.express as px

In [ ]:

# Create a 3D scatter plot
fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z, mode='markers')])

# Add lines for each connection
for connection in connections:
    fig.add_trace(
        go.Scatter3d(
            x=[x[connection[0]], x[connection[1]]],
            y=[y[connection[0]], y[connection[1]]],
            z=[z[connection[0]], z[connection[1]]],
            mode='lines',
        )
    )


# Display the plot
fig.show()

In [107]:
df

frame                                                  x  \
0       0  [-0.0, 0.07467737048864365, 0.1108770743012428...   
1       1  [-0.0, 0.07479309290647507, 0.1111875027418136...   
2       2  [-0.0, 0.07662329077720642, 0.1094583719968795...   
3       3  [-0.0, 0.0754227265715599, 0.11193176358938217...   
4       4  [-0.0, 0.07687133550643921, 0.1134890168905258...   
..    ...                                                ...   
64     64  [-0.0, 0.02479284629225731, -0.073712401092052...   
65     65  [-0.0, 0.02479284629225731, -0.073712401092052...   
66     66  [-0.0, 0.02479284629225731, -0.073712401092052...   
67     67  [-0.0, 0.02479284629225731, -0.073712401092052...   
68     68  [-0.0, 0.02479284629225731, -0.073712401092052...   

                                                    y  \
0   [0.0, -0.028070135042071342, 0.025105670094490...   
1   [0.0, -0.030101073905825615, 0.021642440930008...   
2   [0.0, -0.03380797058343887, 0.0211855955421924...   
3   [0.0, -0.03365670517086983, 0.0218077041208744...   
4   [0.0, -0.030278075486421585, 0.022360188886523...   
..                                                ...   
64  [0.0, -0.09599307924509048, -0.010923860594630...   
65  [0.0, -0.09599307924509048, -0.010923860594630...   
66  [0.0, -0.09599307924509048, -0.010923860594630...   
67  [0.0, -0.09599307924509048, -0.010923860594630...   
68  [0.0, -0.09599307924509048, -0.010923860594630...   

                                                    z  
0   [0.6717526912689209, 0.6715698838233948, 0.323...  
1   [0.6751559972763062, 0.6747398972511292, 0.323...  
2   [0.6765562891960144, 0.6746162176132202, 0.325...  
3   [0.6735761761665344, 0.6716593503952026, 0.319...  
4   [0.678354024887085, 0.6777233481407166, 0.3257...  
..                                                ...  
64  [0.6296744346618652, 0.6260457634925842, 0.327...  
65  [0.6296744346618652, 0.6260457634925842, 0.327...  
66  [0.6296744346618652, 0.6260457634925842, 0.327...  
67  [0.6296744346618652, 0.6260457634925842, 0.327...  
68  [0.6296744346618652, 0.6260457634925842, 0.327...  

[69 rows x 4 columns]

In [116]:
fig = px.scatter_3d(df, x="x", y="y", z="z", animation_frame="frame", opacity=1)
fig.show()

In [118]:
px.scatter_3d(df, x="x", y="y", z="z",  opacity=1)

In [119]:
data = px.data.iris()

In [120]:
data

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     species_id  
0             1  
1             1  
2             1  
3             1  
4             1  
..          ...  
145           3  
146           3  
147           3  
148           3  
149           3  

[150 rows x 6 columns]